# Generated by Django 4.0.6 on 2022-07-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=250)),
                ('studentID', models.CharField(max_length=250)),
                ('subject', models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('Flutter', 'Flutter')], default='----', max_length=250)),
            ],
        ),
    ]
